src/components/Chart/Chart.tsx, src/components/StatisticView/StatisticView.tsx, src/components/Table/Table.tsx, src/events/statistic.ts, src/features/Statistic.tsx, src/hooks/useEventBusForHost.ts, src/hooks/useEventBusForStatistic.ts, src/services/refact.ts
added events and methods for getting data from endpoint
=> Getting data for statistic from endpoint

src/features/Chat.tsx, src/hooks/useEventBusForChat/index.ts, src/hooks/useEventBusForChat/reducer.test.ts
When a chat that’s is streaming has been moved away from, it could be added to a temporary storage where it can continue to receive updates, then when it’s done it can be save thought the history mechanism of the ide, and restored as normal.
… when restoring I guess we’ll need to check if the chat is in temporary storage and use that one if not then take the one given to it by the ide.
rough outline.
- if the chat is streaming, and another is restored / created. put it into a cache.
- if a chat response message comes in and it’s not for the current chat, check the cache if it’s there then add the stream to it.
- do a similar check for the done message, but send a save history event and remove the cached chat.
- When restoring / switching between chats, check the cache first
=> Deltas fix

src/components/CloudLogin/CloudLogin.tsx
PRO tier was not selectable and login procedure was stopping each time we are trying to change a plan.
I've removed hardcoded part in `CloudLogin.tsx` component, Button's `onClick` function.
- Step 1: Start refact-lsp
- Step 2: Start refact-chat-js
- Step 3: Choose Refact Cloud as Setup Option
- Step 4: Choose between FREE or PRO tiers.
=> Fix: Login procedure not breakes up anymore on PRO tier selected

src/components/Tour/Tour.tsx, src/components/Tour/TourBox.tsx, src/components/Tour/TourBubble.tsx
- Problem: Current Tour Bubbles are stretching of insane dimensions on wide areas of view.
- Solution: Adjustment of TourBox component and Tour component itself. Implementation of `bubbleContainerStyles` to control position and behavior of exact Tour Bubble and limit its width to 550 pixels.
- [Any background context or related links?](https://github.com/orgs/smallcloudai/projects/5/views/1?pane=issue&itemId=75268877)
- Step 1: Click on Menu icon at top right corner
- Step 2: Click on `Restart Tour` button
- Step 3: Click `Next` button on each Bubble to move to the next Bubble.
=> Fix: Tour Bubble size limitation

src/components/ChatForm/ChatForm.tsx
- Problem: Hint is disappearing even if textarea is empty and `completion.commands` array is empty.
- Solution: Fix of condition for placeholder render.
- [Any background context or related links?](https://github.com/orgs/smallcloudai/projects/5/views/1?pane=issue&itemId=70283681)
- Step 1: Start a New Chat
- Step 2: "Type @ for commands" hint should be already visible
- Step 3: Try to write some commands or text
- Step 4: Make textarea clear again
- Step 5: Hint should be visible
=> Fix: Type @ for commands hint

src/components/ChatForm/PromptSelect.tsx, src/components/Select/Select.tsx, src/components/Select/select.module.css
- Problem: Strange scrolling behavior of a select if there are more options to choose and they don't feet inside of screen boundaries.
- Solution: Change position type to `popper` and added ability to customize it in other selects if needed.
- [Any background context or related links?](https://github.com/orgs/smallcloudai/projects/5/views/1?filterQuery=alashchev17&pane=issue&itemId=75269274)
- Step 1: Start a New Chat
- Step 2: Choose either a model or system prompt settings within a select
=> Fix: Select scroll behavior

src/__tests__/ChatCapsFetchError.test.tsx, src/__tests__/DeleteChat.test.tsx, src/__tests__/RestoreChat.test.tsx, src/__tests__/StartNewChat.test.tsx, src/app/middleware.ts, src/app/store.ts, src/components/ChatForm/ChatForm.test.tsx, src/features/Chat/Chat.test.tsx, src/hooks/useGetCapsQuery.ts, src/hooks/useGetPing.ts, src/hooks/useGetPromptsQuery.ts, src/hooks/useGetStatisticDataQuery.ts, src/hooks/usePing.ts, src/services/refact/consts.ts, src/services/refact/index.ts, src/services/refact/ping.ts, src/utils/mockServer.ts
- After logging in in an ide, the lsp restarts, chat can make calls to the lsp before it has had the chance to start.
- Added a call to `/v1/ping`, this will be used to skip other requests until ping works.
1. Build chat,
2. link it to vscode
3. logout
4. login
5. click new chat.
Or: when running in dev
1. run `npm run dev`
2. Open the network tab
3. stop the lsp.
4. refresh
5. click new chat.
Only `ping` should be called.
https://github.com/orgs/smallcloudai/projects/5/views/1?pane=issue&itemId=78627164
=> wip(ping): add ping service and hook.

src/components/ChatForm/ChatForm.tsx
=> style: remove wrap from help menu

src/components/Markdown/CodeBlock.tsx, src/components/Markdown/convertMarkdownToDiffChunk.ts, src/services/refact/diffs.ts
Fix: paste patch code block
https://github.com/orgs/smallcloudai/projects/5/views/1?pane=issue&itemId=78657574
When using a prompt that makes a patch, the patch is shown to the user, but when clicking copy he patch is pasted as is into the ide.
I've decieded to use the `preview` function to open the file.
use this prompt 
```
Use patch() to fix the following problem
Expected ":"
at the lint
def __init__(self, x, y, vx, vy)
then tell if the generated patch is good in one sentence.
```
Click the diff button.
https://github.com/orgs/smallcloudai/projects/5/views/1?pane=issue&itemId=78657574
We'll need to test this for file renames.
=> Diff code block

src/features/Chat/Thread/reducer.ts
- Problem: System Prompt was not saving on opening a new chat
- Solution: Adjusted `newChatAction` listener. Now passing to the next chat instance `state.system_prompt` as well.
- [Any background context or related links?](https://github.com/orgs/smallcloudai/projects/5/views/1?filterQuery=alashc&pane=issue&itemId=80036824)
- Step 1: Open a New Chat
- Step 2: Select a System Prompt
- Step 3: Open a New Chat and see the same System Prompt selected
=> Fix: System Prompt saves after opening a New Chat

src/__fixtures__/chat.ts, src/__fixtures__/history.ts, src/__tests__/DeleteChat.test.tsx, src/__tests__/RestoreChat.test.tsx, src/components/Chat/Chat.tsx, src/features/Chat/Thread/actions.ts, src/features/Chat/Thread/reducer.ts, src/features/Chat/Thread/selectors.ts, src/features/Chat/Thread/types.ts, src/hooks/useSendChatRequest.ts
- Problem: User had no way to get information in existing chat window what agentic capabilities mode it is using. Actual mode of a chat was not stored properly in history and within a chat. All chat threads were working based on a agentic capabilities selected for whole application.
- Solution: Adjusted Application's UI a bit to show up a mode, also added a new selector to get `tool_use` of a current thread. Created a field of `tool_use` within thread as well, so it could rely on its own `tool_use` and not a global one (global one is needed to remember which mode user has selected previously, but in terms of lots of chats - proper way is to save thread's `tool_use` as well)
- [First issue](https://github.com/orgs/smallcloudai/projects/5/views/1?pane=issue&itemId=80350424)
- [Second …
=> Fix: Showing chat mode & Saving tool_use in a chat thread store

src/contexts/AbortControllers.tsx, src/features/App.tsx, src/features/Chat/Thread/reducer.ts, src/features/Chat/Thread/types.ts, src/features/Chat/Thread/utils.ts, src/hooks/useAbortControllers.ts, src/hooks/useSendChatRequest.ts, src/utils/test-utils.tsx
Stop button should work after restoring from cache.
+ When the user moves from a chat while it's still streaming and opens it again the stop button no longer works.
+ Added a hash-map for the abort functions which is hoisted into a context object at the top of the app.
1. Start a chat
2. Click home.
3. Click back on the chat.
4. Click stop, chat should stop.
Also, check that the tool_use property on the thread is retained.
https://github.com/orgs/smallcloudai/projects/5/views/1?pane=issue&itemId=81525640
=> fix(stop chat after cache restore, and ensure tool_use is defined)

src/components/ChatContent/AssistantInput.tsx
- Problem: [➕ Diff ] button was rendered even if user didn't select any lines of code.
- Solution: Get selected snippet from the store and calculate amount of code lines within selection. If amount of lines is greater than 0, so we can render [➕ Diff ] button
- Diff workflow
- Step 1: Link current branch to the `refact-vscode` repository or rather make a build for `refact-intellij` repository and launch an extension/plugin in debug mode
- Step 2: Ask chat model to generate some code chunk
- Step 3: Try to select and unselect code within the editor
Expected Result:
- If lines are selected: [➕ Diff ] button should appear near to [ New File ] and [ Copy ] buttons
- If lines are unselected: [➕ Diff ] button should disappear
=> Fix: Conditional rendering of [➕ Diff ] button

src/features/History/historySlice.ts
1. Make a lot of chats, 
2. History shouldn't be more than 100
3. The chats will be removed by `updateAt` value
https://github.com/orgs/smallcloudai/projects/5/views/1?pane=issue&itemId=79233318
=> Limit history to 100 items

src/components/ChatForm/FilesPreview.tsx, src/components/ChatForm/useCommandCompletionAndPreviewFiles.ts, src/services/refact/types.ts
- Problem: Attached file was previewed with `:%START_LINE%-%END_LINE%` and not with `:%START_LINE%-%CURSOR_LINE%`
- Solution: Adding additional check to synchronize response from LSP for `v1/command-preview` and actual active file within the IDE
- [Any background context or related links?](https://github.com/orgs/smallcloudai/projects/5/views/1?pane=issue&itemId=81524949)
- Step 1: Start a new chat in IDE
- Step 2: Open any file inside the editor
- Step 3: Attach this file via checkbox
- Step 4: Move the cursor within editor's window and see how attachment changes
=> Fix: Cursor line showing for attached file

src/components/ChatForm/ChatForm.tsx, src/components/ChatForm/useCheckBoxes.ts
- Problem: After very first user interaction on checkbox, it was behaving not as expected, especially, after trying to select lines after explicitly checking up the checkbox - it was not counting lines correctly.
- Solution: Implemented 2 different interacted states for both file attachment and lines selection checkboxes, adjustment of `useAttachSelectedSnippet` logic within `useEffect`.
- [Any background context or related links?](https://github.com/orgs/smallcloudai/projects/5/views/1?filterQuery=alashchev17&pane=issue&itemId=78566457)
- Step 1: Start a new chat, then select some code
- Step 2: Uncheck lines selection checkbox, remove lines selection
- Step 3: Try to select lines in editor's tab again
- Step 4: Check the lines selection checkbox, then click on the editor's tab (to not …
=> Fix: Lines selection checkbox behavior

src/components/Markdown/Markdown.tsx, src/events/index.ts, src/hooks/index.ts, src/hooks/useEventBusForApp.ts, src/hooks/useEventBusForIDE.ts, src/hooks/usePatchActions.ts
Adds an event that allows the ide to send the next pin message to be run.
1. Use this branch for vscode https://github.com/smallcloudai/refact-vscode/pull/149
2. Build and link chat.
3. Ask `rename Frog to bird with out changing any files`
4. Click `accept and continue` to go to the next patch
The codeLens looks a bit long.
The patch can be slow to open a file :/
=> Show patch ticket from ide

src/events/index.ts, src/features/App.tsx, src/hooks/useEventBusForIDE.ts
- Problem: CodeLens in VSCode were lacking of actual chat state, chat window was not opening as expected
- Solution: Implemented a handler to remember current chat page in VSCode, also fixed types for `refact-vscode` ability to build up.
- [Any background context or related links?](https://github.com/orgs/smallcloudai/projects/5/views/1?filterQuery=alashchev&pane=issue&itemId=82882638)
- Edit your `customization.yaml`, set in every code_lens instruction of `auto_submit` to `false`
- Try to click "Explain" within the code editor's fragment of code
- Chat should open up a new window and paste the snippet from `customization.yaml` and place it in a text area.
- Relies on [#150](https://github.com/smallcloudai/refact-vscode/pull/150)
=> Fix: CodeLens workflow

src/components/ChatForm/ChatForm.tsx, src/components/ChatForm/useCheckBoxes.ts
- Problem: Feature of remembering user's line selection and attached file was lost
- Solution: Recovering of that functionality, little adjustment on setting checkboxes as interacted. If textarea is empty, checkboxes will not remember user's selection.
- [Any background context or related links?](https://github.com/orgs/smallcloudai/projects/5/views/1?pane=issue&itemId=78566457)
=> Fix: Checkboxes set as interacted on chat form change, if it's not empty

src/features/Chat/Thread/reducer.ts, src/features/History/historySlice.ts
When clicking explain and away from the chat, the chat would continue to show it's streaming event when done.
Also sets prevent send so that the user decide to resume uncalled tools.
1. build and run vscode
2. click explain in code lens
3. navigate to history after the chat opens.
4. observe chat stop streaming when done.
=> fix(done streaming): thread maybe in the cache when generating the title

src/components/ComboBox/ComboBox.tsx, src/events/index.ts, src/hooks/useEventBusForIDE.ts
- Problem: To switch back to IDE you need to click with mouse inside of editor.
- Solution: Implementation of new handler will enhance user experience by providing an ability to switch between chat and code just with one press of Escape character.
- [[vscode] Esc in chat input box -> set focus back on IDE editor](https://refact.fibery.io/Software_Development/Task/vscode-Esc-in-chat-input-box---set-focus-back-on-IDE-editor-218)
- Step 1: Open a new chat
- Step 2: Press `Escape` on your keyboard (important note: you should be focused on textarea)
- Step 3: See how your active tab switched from UI to actual editor (if it exists)
=> Feature: Focusing on editor in IDE on Escape press

src/features/History/historySlice.ts
- Problem: Title wasn't generated if streaming was finished in history view.
- Solution: First user message was captured not from relative thread, but from global state itself. Now all the logic relies on thread being initiated before user went to history view.
- [Can't create title in background](https://refact.fibery.io/Software_Development/UI-UX-133#Task/Can't-create-title-in-background-215)
1. Step 1: Start a new chat thread, ask anything to model
2. Step 2: After streaming has started, go to main view
3. Step 3: After finalization of model's response, chat title should be generated properly.
=> Fix: Title generation in background

src/app/middleware.ts, src/components/Chat/Chat.tsx, src/features/Chat/Chat.tsx, src/services/refact/prompts.ts
- Problem: On `/v1/customization` fetch, error message was set by middleware and not from actual query. Also, prop drilling was present from `features/Chat.tsx` component.
- Solution: Setting error message directly in query function, reduction of prop drilling by moving selectors deeper in components tree
- [Bad error message on syntax error in customization.yaml](https://refact.fibery.io/Software_Development/Task/Bad-error-message-on-syntax-error-in-customization.yaml-219)
1. Step 1: Add to your `customization.yaml` some illegal code, for example: `aaaaa aaaaa"`
2. Step 2: Try to open a new chat
3. Step 3: Better error message should appear
=> Fix: Better errors for /v1/customization & ChatComponent refactoring

src/__fixtures__/chat.ts, src/__fixtures__/history.ts, src/__tests__/DeleteChat.test.tsx, src/__tests__/RestoreChat.test.tsx, src/features/Chat/Thread/actions.ts, src/features/Chat/Thread/reducer.ts, src/features/Chat/Thread/types.ts, src/features/History/historySlice.ts
- Problem: After resuming of chat with uncalled tools previously, title wasn't generated.
- Solution: Additional flag of `isTitleGenerated` and updated logic for title generation
- [Can't create title in background](https://refact.fibery.io/Software_Development/Task/Can't-create-title-in-background-215)
- Step 1: Use CodeLens 'Explain' of 'Find Problems' with `auto_submit` flag set to `true`
- Step 2: Immediately go to history view page, where all chat threads are located
- Step 3: Return to the chat when streaming is done
- Step 4: Click on 'Resume' to continue response generation coming from model
- Step 5: Go to history view again, wait for the end of streaming
- Step 6: If model didn't try to call any tools, title should be generated correctly. If model called tools, go back to step 3
=> Fix: Title generation in background after resuming of chat

src/features/Chat/Thread/actions.ts, src/utils/index.ts, src/utils/scanForDuplicates.ts, src/utils/takeFromEndWhile.ts, src/utils/utils.test.tsx
Tool calls can create a loop, it usually happens when using `cat` a lot.
setting `only_deterministic_messages` on the request to `v1/chat` will stop this loop.
This PR scans the messages to see if it ends with a sequence of `assistant` and `tool` messages, then checks those messages to see if `function.name`, `function.arguments`, and `tool.content` are duplicated inn another message.
if there is a duplicate, the `only_deterministic_messages` property is set to true. and the loop stops.
TODO:
We might want to notify the user that the their was a loop.
1. Start the lsp with the workspace `-w` set to the directory of the lsp source code. `-w .`
* open the network tabs.
2. Open chat and ask gpt-4o-mini  to `add a swim method` with the explore tools
3. this could cause a loop, now it will …
=> wip(tool loop): set `onlyDeterministicMessages` if a duplicate tool call and result is found.

.storybook/preview.tsx, src/__fixtures__/chat.ts, src/components/ChatContent/ChatContent.stories.tsx, src/components/ChatContent/ChatContent.tsx
when finding a diff message, `{role: "assistant", content: "", tool_calls[{....}]` would be skipped.
```ts
const restInTail = takeWhile(tail, (message) => {
const isEmptyAssistantMessage =
isAssistantMessage(message) && !message.content;
return (
isDiffMessage(message) ||
isToolMessage(message) ||
isEmptyAssistantMessage
);
});
```
This would hide some of the tool messages
Check in story book
https://refact.fibery.io/Software_Development/UI-UX-133#Task/One-of-two-patch()-calls-visible-320
=> Tools: group diffs and tool results, but not tool_calls

src/components/Markdown/Markdown.tsx
- Problem: Currently headings parsed by frontend from Markdown are too big
- Solution: Reduction of size and margins
- [Headers in assistant responses are ugly](https://refact.fibery.io/Software_Development/UI-VS-347#Task/Headers-in-assistant-responses-are-ugly-151)
- Click "Explain" codelens instruction to test out sizes of headings
=> Fix: Adjusted heading in Assistant's response

package-lock.json, package.json, src/app/middleware.ts, src/app/store.ts, src/components/Chat/Chat.tsx, src/components/ChatContent/ChatContent.tsx, src/components/ChatContent/UserInput.tsx, src/components/ChatForm/ChatForm.tsx, src/components/ChatForm/RetryForm.tsx, src/components/Dropzone/Dropzone.tsx, src/components/Dropzone/index.tsx, src/features/AttachedImages/imagesSlice.ts, src/features/AttachedImages/index.ts, src/features/Chat/Thread/utils.ts, src/features/History/historySlice.ts, src/hooks/useAttachedImages.ts, src/hooks/useSendChatRequest.ts, src/services/refact/chat.ts, src/services/refact/types.ts
User can add images to chat by either clicking a button or drag and drop.
Reties also work
Allow the suer to drop images into chat.
1. run the lsp with BYOK
2. run chat
3. Click the image icon
4. add files
5. ask question about the images
6. send chat
repeat for drag and drop, but also include non-image files
Merge once it works without needing byok
=> wip(feat/paste): images dropzone

src/components/ChatContent/ToolsContent.tsx, src/components/Command/Command.module.css, src/components/Command/Markdown.tsx, src/components/Reveal/reveal.module.css
- Problem: `tree()` tool in collapsed state was not hiding content which overflows, which led to unexpectedly increased scroll height
- Solution: Hiding overflow for collapsible root element
- [ToolsContent are not hiding overflow inside, if tool content is collapsible](https://refact.fibery.io/Software_Development/UI-UX-133#Task/ToolsContent-are-not-hiding-overflow-inside,-if-tool-content-is-collapsible-342)
- Step 1: Ask in the chat to call tree
- Step 2: Expand tool content, then check scroll
- Step 3: Click on "Click for more" to expand collapsible, scroll should increase correctly
=> Fix: ToolsContent overflow issue

src/app/middleware.ts, src/app/store.ts, src/components/ChatContent/ChatContent.tsx, src/features/TipOfTheDay.tsx
Next was being called when the Tip of the day component mounts, causing it to change it's children and remount.
The cases for incrementing the tip have been added to some middleware.
- Step 1: One a chat and redux dev tools,
- Step 2: Click "new chat"
- Step 3: tipoftheDay/next should only have been called once.
- Fixes https://refact.fibery.io/Software_Development/UI-chat-js-133#Task/Tip-of-the-day-is-jumping-over-by-one-tip-each-time-we-are-starting-a-new-chat-341
=> Fix tip of the day double next

src/hooks/usePatchActions.ts, src/services/refact/diffs.ts
Update to diff api, it should be able to tell the user when the patch is already applied.
- Step 1: Build chat `npm run build`
- Step 2: create a link `npm link`
- Step 3: goto vscode project
- Step 4: `npm link refact-chat-js`
- Step 5: `npm run compile -- --watch`
- Step 6: start asking chat to make changes
- Step 7: click "auto apply" a few times.
See video in ticket.
https://refact.fibery.io/Software_Development/UI-chat-js-133#Task/Pin-already-appied-381
There maybe some bugs in the lsp :/
=> feat(already_applied): so info if patch is already applied.

src/components/Command/Command.module.css
- Problem: Now, if the tool is returning as output small message, actual box of it will be not covering all available area.
- Solution: `min-width` set up
- Step 1: Call `tree` tool in small project, it should now look better
=> Fix: Minimal width for tools execution output

src/components/Chat/Chat.tsx, src/components/IntegrationsView/IntegrationForm/IntegrationForm.tsx, src/features/Chat/Thread/actions.ts, src/features/Chat/Thread/reducer.ts, src/features/Chat/Thread/selectors.ts, src/features/Chat/Thread/types.ts, src/hooks/useSendChatRequest.ts, src/services/refact/chat.ts, src/services/refact/integrations.ts
=> Wip smart links button

src/components/ChatForm/ToolConfirmation.module.css
- Problem: layout of tool confirmation popup was shifted if confirmation was needed not on the first tool call, but later on in the chat with lots of messages present. In the light theme, text was not changed to black, it was white
- Solution: Adjusted styles of `ToolConfirmationCard`
- [Tool Confirmation: Layout shift & colors issue in light theme](https://refact.fibery.io/Software_Development/UI-UX-133#Task/Tool-Confirmation-Layout-shift-colors-issue-in-light-theme-434)
=> Fix: Tool Confirmation layout & styling

src/components/ChatForm/ChatForm.tsx, src/features/Config/configSlice.ts
Run in jetbrains there shouldn't be a button in the textarea to add an image.
=> fix(jb images): remove "add image" button from jetbrains.

src/components/ChatLinks/ChatLinks.tsx
Handle goto actions.
Goto actions should try to go the most logic next page.
https://refact.fibery.io/Software_Development/Week1209-by-state-420#Task/Make-goto-settings-action-work-509
=> fix(chat links): handle go to actions.

src/features/History/historySlice.ts
The history limit was not being imposed, allowing the chat to go over 100 items.
It seems to be an issue with the reducer either mutating the proxy object or returning a different state object.
- Step 1: checkout alpha, Make a lot of chats. more than 100. (checking redux for the number of entries)
- Step 2: checkout this branch.
- Step 3: Ask a question.
- Step 4: The number of save chat should be 100.
https://refact.fibery.io/Software_Development/Week1209-by-state-420#Task/Limit-chat-history,-too-slow!-506
=> Fix history limit

src/components/Chat/Chat.tsx, src/features/Chat/Chat.test.tsx, src/features/Chat/Thread/reducer.ts, src/hooks/useLinksFromLsp.ts
Sets the model to use to either gpt-4o or cluade when using agent mode.
* Start a new chat
* Tool use should be set to agent by default
* the available models should only be gpt-4o and claude.
* switch to explore to see more models.
=> Agentic defaults

src/components/Chat/Chat.stories.tsx, src/components/ChatForm/ToolConfirmation.module.css, src/components/ChatForm/ToolConfirmation.tsx, src/components/IntegrationsView/IntegrationForm/IntegrationForm.tsx, src/components/IntegrationsView/IntegrationsHeader.tsx, src/components/IntegrationsView/IntegrationsView.tsx, src/components/IntegrationsView/IntermediateIntegration/IntermediateIntegration.tsx, src/components/SmartLink/SmartLink.tsx, src/features/Chat/Thread/types.ts, src/features/History/historySlice.ts, src/features/Integrations/renderIntegrationFormField.tsx, src/features/Pages/pagesSlice.ts, src/hooks/useGoToLink.ts, src/hooks/useLinksFromLsp.ts, src/services/refact/docker.ts, src/services/refact/integrations.ts
- Recommended list of integrations to setup is redirecting to the intermediate page of configuration UI, making user able to choose where to start the setup procedure. Also avoiding save of integration meta from links into cache of history slice.
- If recommended integration from the link is rather cmdline or service, it's command name will be inserted into text field on intermediate page.
- Tool Confirmation UI got adjusted due to deprecation of old `integrations.yaml` feature. Also some styling adjustments were made according to proposals
- Step 1: Click on New Chat
- Step 2: Wait until links are loaded
- Step 3: Click on whatever link that says "configure"
- Step 4: Intermediate page with radio buttons should appear
=> Fix: integrations UI fixes

src/features/Config/configSlice.ts, src/vite-env.d.ts, vite.config.ts
During dev the user may want to change the lsp port.
- Step 1: run chat in dev with `REFACT_LSP_PORT="9001" npm run dev`
- Step 2: request to the lsp should use port 9001.
=> feat(lsp port): allow setting the lsp port during dev.

src/components/IntegrationsView/IntegrationForm/IntegrationForm.tsx, src/components/IntegrationsView/IntegrationsView.tsx
- Problem: after comparing `confirmationRules` and rules from `integr_values`, I was rendering local `confirmationRules`, if rules are different and remote ones, if rules are the same.
- Solution: adjusted ternary expression.
- [🔴 Integration page - deny and confirm editor](https://refact.fibery.io/Software_Development/Current-Week-by-state-358#Task/Integration-page---deny-and-confirm-editor-537)
- Step 1: Open any integration, edit confirmation rules and save
- Step 2: Reopen integration
- Step 3: Rules should be rendered from the LSP's output
=> Fix: Confirmation rules proper rendering

src/components/Buttons/Buttons.tsx, src/components/ChatLinks/UncommittedChangesWarning.tsx
When running in an ide, the `upgrade to pro` button didn't work.
the `useOpenUrl` hook has been reused so the ide opens the url.
Commit warning message stayed on screen while chat was streaming, this has been removed.
- Step 1: Build chat and run it in an ide.
- Step 2: Logout ad back in as a free user
- Step 3: Send about 15 to 20 messages.
- Step 4: There should be a warning about usage limits.
- Step 5: click the upgrade button
- Step 6: the ide should open to refacts upgrade page.
Step: 7 open a project with uncommitted changes.
Step 8: There should be a warning.
Step 9: send a message
Step 10: the warning should disappear while the chat is streaming. 
https://refact.fibery.io/Software_Development/Release-6.1-433#Task/Uncommitted-warning----remains-on-screen-even-when-the-streaming-sta …
=> UI fixes links and commit warning

src/components/IntegrationsView/IntegrationForm/IntegrationForm.tsx, src/components/SmartLink/SmartLink.tsx, src/services/refact/integrations.ts
- Support for additional flag for smartlinks
- [UI Smartlink enable only with tool](https://refact.fibery.io/Software_Development/Release-6.1-433#Task/UI-Smartlink-enable-only-with-tool-589)
- Step 1: Try to create a new configuration for integration (for example, postgres)
- Step 2: Smartlink "Test" should be disabled
- Step 3: Apply changes to save integration
- Step 4: Smartlink "Test" should be enabled
- Step 5: Modify any fields within integration form
- Step 6: Smartlink "Test" should be disabled
=> Fix: Integration smartlinks with extra flag are getting disabled on conditions

src/components/IntegrationsView/IntegrationsView.tsx
- Problem: when setting up `service_*` integration, integration header was showing cmdline for all of custom integrations.
- Solution: taking original type of custom integration based on server data instead of having `cmdline` hardcoded.
=> Fix: Displaying correct type of integration in Integration Header

src/__tests__/isAbsolutePath.test.ts, src/app/middleware.ts, src/debugConfig.ts, src/hooks/useLinksFromLsp.ts, src/utils/isAbsolutePath.test.ts
- Problem: previous implementation was not covering UNIX paths, also, `v1/integration-get` was not invalidating cache properly.
- Solution: using existing `isAbsolutePath()` and written tests for that function to be sure that it works correctly. Also made a listener in middleware to reset API state to make sure that `v1/integration-get` will be triggered on return.
- [VERIFIED AND STILL THERE -- UI save and return to config, doesn't load the updates values](https://refact.fibery.io/Software_Development/Week1223-by-state-436#Task/508)
- Step 1: Open working postgres configuration
- Step 2: Click on "Test" smartlink
- Step 3: Ask model to change database name (or any other property) to be different
- Step 4: When [Save and return] link is available, click on that one
- Step 5: Values of …
=> Fix: using `isAbsolutePath()` to check for paths in link_goto & invalidating of cache for `v1/integration-get`

src/components/Chat/Chat.tsx, src/components/ChatForm/ChatControls.tsx, src/components/ChatForm/ChatForm.stories.tsx, src/components/ChatForm/ChatForm.test.tsx, src/components/ChatForm/ChatForm.tsx, src/hooks/useCapsForToolUse.ts
- Problem: If tool use was set to "Explore", models which don't support tools were not filtered out.
- Solution: Adjustment of `usableModels` reduce call to include that condition as well.
- Extra: Small refactoring of ChatForm, Chat components, reduction of props getting passed down to the components tree (now consuming state directly from RTK Store)
- [No tools models behavior](https://refact.fibery.io/Software_Development/Task/No-tools-models-behavior-613)
- [Chat mode in IDE](https://refact.fibery.io/Software_Development/Week1223-by-state-436#Task/Chat-mode-in-IDE-614)
=> Fix: If model doesn't support tools, exclusion from list of usable models & simplification of props for ChatForm

src/components/Chat/Chat.tsx, src/components/ChatForm/ChatForm.test.tsx, src/components/ChatForm/ChatForm.tsx, src/components/ChatForm/ToolConfirmation.tsx, src/components/Toolbar/Toolbar.tsx, src/features/Chat/Thread/actions.ts, src/features/ToolConfirmation/confirmationSlice.ts, src/hooks/useGoToLink.ts, src/hooks/useSendChatRequest.ts, src/services/refact/chat.ts
- Problem: even for commands that need confirmation, users were not able to just deny tool without resubmitting previous message.
- Solution: adding support for denying tools just within chat.
- Extra: refactoring of Chat, ChatForm, ToolConfirmation components, taking `rejectToolUsage` and `confirmToolUsage` were needed without extra prop drilling.
- [Implement tool refusal](https://refact.fibery.io/Software_Development/Week1223-by-state-436#Task/Implement-tool-refusal-621)
=> Feat: Support of denying tools on run from Tool Confirmation popup

src/hooks/useCapsForToolUse.ts, src/services/refact/chat.ts
- Step 1:
- Step 2:
- ...
- Fixes #123
- Closes #456
=> More tokens / more models

src/components/ChatContent/ChatContent.tsx, src/hooks/useLinksFromLsp.ts
- [Uncommitted warning gets dragged along in "Explore" mode](https://refact.fibery.io/Software_Development/Task/Uncommitted-warning-gets-dragged-along-in-Explore-mode-641)
=> Fix: hiding uncommitted changes warning if chat mode is explore

src/app/middleware.ts, src/components/ChatForm/ToolConfirmation.tsx, src/features/ToolConfirmation/confirmationSlice.ts, src/hooks/useSendChatRequest.ts, src/services/refact/chat.ts, src/services/refact/tools.ts
- [Confirmation use real link to settings, no link if there's no config file](https://refact.fibery.io/Software_Development/Task/Confirmation-use-real-link-to-settings,-no-link-if-there's-no-config-file-654)
- [For Patch adjust confirmation: Expecting messages in /tools-check-if-confirmation-needed](https://refact.fibery.io/Software_Development/Task/For-Patch-adjust-confirmation-Expecting-messages-in-tools-check-if-confirmation-needed-658)
- [Conflict between confirmation and "assistant without tool calls, resume"](https://refact.fibery.io/Software_Development/Task/Conflict-between-confirmation-and-assistant-without-tool-calls,-resume-652)
- [Confirmation stays when hitting F1](https://refact.fibery.io/Software_Development/Task/Confirmation-stays-when-hitting-F1-653)
=> Fix: Better Tool Confirmation popup

src/__fixtures__/confirmation.ts, src/components/ChatContent/ChatContent.tsx, src/components/ChatContent/ContextFiles.tsx, src/components/ChatForm/ChatForm.tsx, src/components/ChatForm/ToolConfirmation.stories.tsx, src/components/ChatForm/ToolConfirmation.tsx, src/components/IntegrationsView/IntegrationForm/IntegrationAvailability.tsx, src/components/IntegrationsView/IntegrationForm/IntegrationForm.tsx, src/components/IntegrationsView/IntegrationsHeader.module.css, src/components/IntegrationsView/IntegrationsHeader.tsx, src/components/Markdown/CodeBlock.tsx, src/components/Markdown/Markdown.tsx, src/features/App.tsx, src/features/Integrations/Integrations.tsx, src/features/Integrations/renderIntegrationFormField.module.css, src/hooks/useSendChatRequest.ts
- [Confirmation use real link to settings, no link if there's no config file](https://refact.fibery.io/Software_Development/Release-6.1-433#Task/Confirmation-use-real-link-to-settings,-no-link-if-there's-no-config-file-654)
- [UI Smartlink enable only with tool](https://refact.fibery.io/Software_Development/Task/UI-Smartlink-enable-only-with-tool-589)
- [The first press of Resume (interrupted chat) does not resend the message](https://refact.fibery.io/Software_Development/Release-6.1-433#Task/The-first-press-of-Resume-(interrupted-chat)-does-not-resend-the-message-684)
- [Hide return button in chat if `project.path` includes `project_summary.yaml`](https://refact.fibery.io/Software_Development/Task/Hide-return-button-in-chat-if-project.path-includes-project_summary.yaml-699)
=> Fix: Release hotfixes

src/components/ChatForm/ChatControls.tsx, src/features/Chat/Thread/reducer.ts, src/features/History/historySlice.ts
- [Can't turn off reasoning slider in existing chat](https://refact.fibery.io/Software_Development/Task/Can't-turn-off-reasoning-slider-in-existing-chat-818)
=> Fix: Reasoning switch hiding in different from AGENT chat modes & better management of setting of a mode for a new chat

src/components/ChatForm/ChatForm.tsx, src/components/ChatForm/useInputValue.ts, src/components/ComboBox/ComboBox.test.tsx, src/components/ComboBox/ComboBox.tsx, src/components/TextArea/TextArea.tsx
- [@file duplicates path](https://refact.fibery.io/Software_Development/Task/file-duplicates-path-839)
- Step 1: Type @file+Space
- Step 2: Paste path to file
- Step 3: Path should be inserted once
=> Fix: Preventing frequent double-pastes from IDE in Combobox

src/components/ChatForm/ChatForm.tsx
- Provides retry for all messages in the chat if user clicks `Click to retry` in error callout, if messages are not empty array and if `state.chat.error` contains the error message (so in that case we can say, that this error is from the chat itself, not from somewhere else in the app)
- Note: Tested with erroring integration config files. If error is permanent, then this retry will not get rid of error. This fix will give the simplification of user flow by minimizing amount of steps to get chat working after error message has appeared.
- [Bug - When press "Click to retry" last message is deleted and last but one message is re-requested](https://refact.fibery.io/Software_Development/Sprint-2025-02-10-495#Task/Bug---When-press-Click-to-retry-last-message-is-deleted-and-last-but-one-message- …
=> Fix: resending messages while clicking error callout
