src/contexts/config-context.tsx
src/events/statistic.ts
src/hooks/useEventBusForStatistic.ts

Removes the cache from the statistics dispaly

Statistics remove cache

---

package-lock.json
package.json
src/hooks/useEventBusForChat/index.ts
src/services/refact.ts

fix: Assistant message can be null

Openai api update

---

package-lock.json
package.json
src/components/ChatForm/ChatForm.test.tsx
src/components/ChatForm/ChatForm.tsx
src/components/ChatForm/usePreviewFileRequest.ts
src/components/ChatForm/utils.ts
src/components/ComboBox/ComboBox.test.tsx
src/components/ComboBox/ComboBox.tsx

Done:
[x] do not send requests for preview on EVERY entered symbol in textbox (UI), as it makes UX super laggy, prob needs some extra logic.
Todo: 
[ ] Attach selected text as a checkbox even when chat has messages (not only on start)
[] moving from at-file to at-file-search when checkbox “attach file” in chat is checked and vecdb is enabled.
Maybe:
[ ] Highlight of at-commands (backend is ready), frontend will need a fair amount of work

Valerii fixes 062024

---

src/components/CloudLogin/CloudLogin.stories.tsx
src/components/CloudLogin/CloudLogin.tsx
src/features/App.tsx
src/hooks/useLogin.ts

Fixed an issue where setup host is called twice and an issue when loigng out which creted a new request ticket.

Fix relogin

---

index.html
src/components/ChatForm/RetryForm.tsx
src/components/ComboBox/ComboBox.tsx
src/features/Config/configSlice.ts
src/hooks/useOnPressedEnter.ts

TODO: add this option to the IDEs and remove the setting from the index.html

feat: add shit + enter to submit option to chat.

---

src/app/storage.ts
src/app/store.ts
src/features/TipOfTheDay.tsx
src/features/Tour.tsx

Fixes: Max storage limit reached.

fix: localStorage max size

---

src/features/App.tsx

https://github.com/orgs/smallcloudai/projects/5/views/1?pane=issue&itemId=78607975

fix: opening chat when there is no history and no tour in progress

---

src/components/ChatContent/ToolsContent.tsx
src/services/refact/types.ts

- Tools were counted in an general number, there was no clearance about how many times did chat use some specific tool
- Changed display logic and wrote small `ToolUsageDisplay` component to render all data if condition is satisfying. Also, added `toolUsageAmount` variable to collect all tools by its names and get amount of their calls
- [Any background context or related links?](https://github.com/orgs/smallcloudai/projects/5/views/1?filterQuery=alash&pane=issue&itemId=78756604)
- Step 1: Start a new chat or open an existing one
- Step 2: Use various tools with @ inside, so model will use some tools
- Step 3: Try to use them in different ways to see how it's being rendered

Fix: Tools counter

---

src/features/History/historySlice.ts

- When chat got created by user, title was cut off any non-latin character.
- Modified regex rule inside of `historySlice`, especially in `saveChat` reducer.
- [Any background context or related links?](https://github.com/orgs/smallcloudai/projects/5/views/1?filterQuery=alash&pane=issue&itemId=78863105)
- Step 1: Start a New Chat
- Step 2: Write any message (make sure that first letters are non-latin)
- Step 3: Get the result!

Fix: Chat title acceptance of non-latin characters 

---

src/components/Tour/TourBox.tsx
src/components/Tour/TourBubble.tsx
src/components/Tour/TourEnd.tsx
src/components/Tour/TourTitle.tsx
src/components/Tour/Welcome.tsx

- Tour was not appearing properly in JetBrains version of Product, because of appearance setting issues.
- I've refactored an existing code related to appearance, changed a bit logic for conditional style changing. Also, I've replaced `useThemeContext()` hook for `useAppearance()` hook, because that one is more appropriate to use.
- [Any background context or related links?](https://github.com/orgs/smallcloudai/projects/5/views/1?pane=issue&itemId=78346278)
- Step 1: Open a Menu Dropdown 
- Step 2: Restart a Tour
- Step 3: Check for results

Fix: Tour appearance

---

src/components/Markdown/Pre.tsx

- Problem: Copy button was appearing on the left side, moving right the code sample.
- Solution: Adjusted layout for Pre element for web.
- [Any background context or related links?](https://github.com/orgs/smallcloudai/projects/5/views/1?filterQuery=alashchev17&pane=issue&itemId=76108737)
- Step 1: Start new chat
- Step 2: Ask a model to write any code
- Step 3: See the result

Fix: Copy button in the web

---

src/components/StatisticView/StatisticView.tsx

- Statistics view was crashing because was trying to access statisticData which was undefined.
- Changed a bit logic for waiting for data and rendering a loading spinner.
- Step 1: Open a Dropdown
- Step 2: Click "Your Stats"

Fix: Spinner component render if statisticData is undefined

---

src/components/BringYourOwnKey/BringYourOwnKey.tsx
src/components/Link/Link.module.css
src/components/Link/Link.tsx
src/components/Link/index.ts
src/components/SelfHostingSetup/SelfHostingSetup.tsx
src/hooks/useAppearance.ts

- Links were not taking an accent color from appearance config.
- Created `<Link />` component, that cares about config params and adjusts styles
- [Any background context or related links?](https://github.com/orgs/smallcloudai/projects/5/views/1?filterQuery=alashchev&pane=issue&itemId=75272904)
- Step 1: Logout if signed in
- Step 2: Choose BYOK option or Self-Hosting
- Step 3: Check links inside of those sections

Fix: Links' color styles inside of JetBrains plugin

---

src/components/Toolbar/Dropdown.tsx
src/hooks/useEventBusForIDE.ts
src/services/refact/consts.ts
src/services/refact/index.ts
src/services/refact/path.ts

Move the customisation call to the services directory, and add a hook for it.
1. Step 1:
2. Step 2:
3. ...

WIP: Refactor customisation path service

---

src/components/ChatContent/ContextFiles.tsx
src/components/Link/Link.module.css
src/components/Link/Link.tsx

- Some links had not a correct hover effect.
- Adjusted styles of `Link` component and replaced RadixUI's Link component for self-created in `ContextFiles` component
- [Any background context or related links?](https://github.com/orgs/smallcloudai/projects/5/views/1?pane=issue&itemId=78689456)
- Step 1: Ask a chat to look through files
- Step 2: Hover over file links

Fix: File links hovers

---

src/app/store.ts
src/components/Callout/Callout.module.css
src/components/Callout/Callout.tsx
src/components/Callout/index.ts
src/components/ChatContent/DiffContent.tsx
src/components/ChatForm/ChatForm.tsx
src/features/Errors/warningSlice.ts
src/services/refact/diffs.ts
src/services/refact/types.ts

- Problem: User was not notified about any sort of problems on apply action of a diff
- Solution: Implemented a nice-looking callout which takes an error message from LSP server and renders it near actual `patch()`
- [Any background context or related links?](https://github.com/orgs/smallcloudai/projects/5/views/1?filterQuery=alashchev&pane=issue&itemId=76144171)
- Step 1: Ask chat to create a flappy-bird game using agent capabilities
- Step 2: Apply changes for a file, then press "Unapply" and again "Apply"

Feature: Error Propagation on diffs actions

---

src/components/ChatContent/DiffContent.tsx

- Problem: Empty lines inside of a diff were "eaten" by a utility function `toDiff`
- Solution: Adjusted `toDiff` utility function in the way that it still treated escaped EOLs, but no longer subtracts empty lines (earlier filter function was removing empty lines, because "" in JavaScript is a false value)
- [Any background context or related links?](https://github.com/orgs/smallcloudai/projects/5/views/1?filterQuery=alashchev&pane=issue&itemId=78271865)
- Step 1: Ask chat to create some sort of files using patch() (as well related for a flappy-bird game creation workflow)
- Step 2: See the result
- Any additional information that might be useful during the review process. -->

Fix: Empty lines inside of a diff

---

src/components/Chat/Chat.tsx
src/components/ChatContent/AssistantInput.tsx
src/components/ChatContent/ChatContent.stories.tsx
src/components/ChatContent/ChatContent.tsx
src/components/ChatContent/DiffContent.test.tsx
src/components/ChatContent/DiffContent.tsx
src/components/ChatContent/ToolsContent.tsx
src/components/ChatContent/UserInput.tsx
src/components/ChatContent/index.tsx
src/components/Markdown/CodeBlock.tsx
src/features/Chat/Thread/selectors.ts
src/hooks/useDiffPreview.ts
src/hooks/useSendChatRequest.ts
src/services/refact/diffs.ts
src/utils/index.ts
src/utils/takeWhile.ts

Adds an apply all to multiple diff messages.
currently the lsp seems to break when asking this prompt so I'll need to wait to properly run it :/
1. Prompt with `rename frog class to bird class with out renaming the files`
2. It should respond with some diffs,
3. Apply and unapply these diffs using the `Apply All` and `Unapply All` buttons.
https://github.com/orgs/smallcloudai/projects/5/views/1?pane=issue&itemId=79900913
I had to re-sync this branch after merging the `apply warning` messages branch in to alpha

Group sequential diffs.

---

src/components/Chat/Chat.tsx
src/hooks/useSendChatRequest.ts
src/utils/takeFromLast.ts

Adds information about diff usage to the chat
note: The usage is added in the user message.
1. Ask a question that results in a diff,
2. do not accept any of them and continue chatting
3. There should be a message `💿 user didn't accept the changes in the UI.`
4. Do the same but this time apply the diffs before asking another question
5. There should be a message about which diffs the user applied.
https://github.com/orgs/smallcloudai/projects/5/views/1?pane=issue&itemId=79901129
https://github.com/orgs/smallcloudai/projects/5/views/1?pane=issue&itemId=79901214

Add 💿 messages about diff usage.

---

src/__fixtures__/chat.ts
src/app/middleware.ts
src/events/index.ts
src/hooks/useDiffPreview.ts
src/hooks/useEventBusForIDE.ts
src/hooks/useEventBusForWeb.ts
src/hooks/useOpenUrl.ts

1. Step 1:
2. Step 2:
3. ...
- Fixes #123
- Closes #456

Fix inflated event exports

---

src/components/Toolbar/Dropdown.tsx
src/hooks/useEventBusForIDE.ts
src/services/refact/path.ts

- Problem: Chat's dropdown was not containing a button to navigate and edit privacy.yaml file
- Solution: Implemented special `fetchPath()` function for three different builders within endpoints in `path.ts`, refactored a logic slightly inside of `useEventBusForIDE.ts` file and changed the structure of `Dropdown.tsx` file a bit. Now after click on each of buttons within the dropdown, dropdown closes.
- [Any background context or related links?](https://github.com/orgs/smallcloudai/projects/5/views/1?pane=issue&itemId=80921753)
Open a dropdown in a chat and try to open files

Fix: Edit privacy.yaml & Slight refactoring

---

src/components/Tour/Tour.tsx
src/features/App.tsx

Get rid of the "Cannot update a component (TourBubble) while rendering a different component (InnerApp) error"
Add useEffect to get rid of the error
Run the app and check if it doesn't give this error in the console
https://github.com/orgs/smallcloudai/projects/5/views/1?pane=issue&itemId=80996711

Fix cannot update component error

---

src/components/ChatContent/ChatContent.tsx
src/components/ChatContent/ScrollToBottomButton.tsx
src/components/ChatContent/useAutoScroll.ts

- Problem: Auto-scroll was scrolling without ability to be disabled after some portion of generated content.
- Solution: Adjustment into a `useAutoScroll()` hook to disable auto-scroll when scrollTop offset is different from lastly saved for `0.6 * window.innerHeight` (can be changed to whatever other value). Also, added `handleWheel` handler to either enable autoscroll again if user scrolls towards new content
- [Any background context or related links?](https://github.com/orgs/smallcloudai/projects/5/views/1?pane=issue&itemId=80665919)
1. Step 1: Ask chat to write long story about anything
2. Step 2: Wait until auto-scroll disables

Fix: Auto-scroll adjustment

---

src/components/Chat/Chat.tsx

- Problem: After performance redux refactoring, the chat window received second scrollbar
- Solution: Make Chat component's `overflow-y` option to be `auto` instead of `scroll`
- #114 
Just open chat with current alpha and then with this branch and see result
- Fixes #114

Fix: Double scroll in Chat

---

src/components/Markdown/Markdown.tsx
src/events/index.ts
src/hooks/useEventBusForIDE.ts
src/services/refact/diffs.ts

Adds events to tell the IDE to animate files that are open and about to be changed by a pin message.
This is so the IDE can add an animation to the file if it is open.
1. Check out the branch of vscode https://github.com/smallcloudai/refact-vscode/pull/142
2. Build and link chat
3. create a chat that has a 📍 message
4. click `open` or `apply` (if the file is open).
5. observe an animation :)
Diff workflow

Pin animations

---

src/components/ChatContent/ScrollToBottomButton.tsx

- Problem: Button is too big
- Solution: Adjustment of width/height of the button
- [Any background context or related links?](https://github.com/orgs/smallcloudai/projects/5/views/1?pane=issue&itemId=82227855)

Fix: Scroll to bottom button adjustment

---

src/components/ChatContent/ChatContent.module.css
src/components/ChatContent/UserInput.tsx

- Problem: Currently the `UserInput` by itself is an edit message button
- Solution: Added a new button near user message, so it appear
- [Any background context or related links?](https://github.com/orgs/smallcloudai/projects/5/views/1?pane=issue&itemId=82453175)

Feat: Addition of a separate edit message button

---

src/features/History/historySlice.ts

- Problem: Title was not generating if content of user input got modified (if `@file` command was used, user input got modified and saved as temporal title for chat and was not equal to truncated user input anymore, so title was not generated)
- Solution: Provided better condition for title generation: thread without generated title has a title equal to empty string.
- [Any background context or related links?](https://github.com/orgs/smallcloudai/projects/5/views/1?filterQuery=title&pane=issue&itemId=78690431)

Fix: Title generation

---

src/components/PageWrapper/PageWrapper.module.css
src/features/App.tsx

- Problem: Double-scroll on history page (list of chat threads)
- Solution: Adjusted height styles for `Sidebar` & `PageWrapper`
- [Any background context or related links?](https://github.com/orgs/smallcloudai/projects/5/views/1?pane=issue&itemId=82763703)

Fix: Double scroll on history page

---

src/components/ChatForm/ChatForm.tsx
src/components/ChatForm/actions.ts
src/components/ChatForm/useInputValue.ts
src/hooks/useGetToolsQuery.ts
src/hooks/useSendChatRequest.ts

- Problem: Auto-submit was not supported
- Solution: Adjusted `useInputValue` hook and used lazy query for tools fetching in `sendMessages`
- [Any background context or related links?](https://github.com/orgs/smallcloudai/projects/5/views/1?pane=issue&itemId=82882638)
1. Step 1: Use `fix/codelens_workflow` branch of `refact-vscode`, current branch of `refact-chat-js` and `new_tab_customization_flag` branch of `refact-lsp`
2. Step 2: Set `auto_submit` flag to `true` for codelens instructions inside of `customization.yaml`
3. Step 3: Try to use it! (tools should be used)

Fix: Auto-submit support for CodeLens

---

src/components/ChatForm/ChatForm.test.tsx
src/components/ComboBox/ComboBox.test.tsx
src/components/ComboBox/ComboBox.tsx

There seems to be some issue when using shift + enter to make a new line in the textarea
This pr moves the logic from onKeyUp to onKeyDown, so if the user releases shift before enter it will not submit the chat.
@valaises and @JegernOUTT have mentioned this issue a few times
1. Start typing in chat
2. hold shift, hold enter, release shift, release enter.
3. In this version it'll add a new line, in the previoue one it would submit.
I'll ask @JegernOUTT to test this one out as they have this problem a lot.
https://github.com/orgs/smallcloudai/projects/5/views/1?pane=issue&itemId=76143663

Shift enter release shift then enter

---

src/components/ChatContent/ChatContent.module.css

- Problem: When code snipped is attached to user's message - edit button is out of boundaries
- Solution: General user input box is now limited on its max width
- [Any background context or related links?](https://github.com/orgs/smallcloudai/projects/5/views/1?pane=issue&itemId=83600128)
- Step 1: Open a new chat
- Step 2: Ask anything to chat, but include selection from IDE (could be huge)
Expected result: Edit Message button is not out of boundaries, should be visible on hover of general area where user input is located

Fix: Edit Message button out of boundaries

---

src/events/index.ts
src/features/App.tsx
src/hooks/useEventBusForIDE.ts

- Problem: `isStreaming` state is not available for vscode extension
- Solution: Exposure of state with additional handler
- [Any background context or related links?](https://github.com/orgs/smallcloudai/projects/5/views/1?pane=issue&itemId=82882855)

Fix: Sending isStreaming state to VS Code

---

src/components/ChatForm/ChatForm.tsx
src/components/ChatForm/useInputValue.ts

- Problem: When user clicks "Explain" or "Find Problems" with some lines selection, it attaches the actual selection and CodeLens snippet in the message instead of just sending an instruction from CodeLens.
- Solution: When CodeLens are clicked, unchecking checkboxes to not include them into actual message of textarea.
- [Any background context or related links?](https://github.com/orgs/smallcloudai/projects/5/views/1?pane=issue&itemId=83797002)
1. Step 1: Try to select some lines in editor
2. Step 2: Click on a CodeLens instruction
3. Step 3: The final message should not contain anything apart from the instruction

Fix: Unchecking checkboxes when running CodeLens instruction

---

src/components/ChatContent/AssistantInput.tsx
src/features/ThreadHistory/ThreadHistory.tsx
src/utils/copyChatHistoryToClipboard.ts
src/utils/fallbackCopying.ts

- Problem: For some reason, `clipboard.writeText()` was not working properly in JetBrains.
- Solution: Usage of `fallbackCopying()` to copy JSON to clipboard, reduction of unnecessary code.
- [[JB] Copy to clipboard (JSON) getting error](https://refact.fibery.io/Software_Development/Task/JB-Copy-to-clipboard-(JSON)-getting-error-222)
1. Step 1: Open an existent chat or create a new one
2. Step 2: Ask anything in chat
3. Step 3: Click on `mode: <mode of your assistant>`, then tiny icon on the right
4. Step 4: Click `Copy to clipboard`
5. Step 5: Check if content got copied

Fix: JSON copying in JetBrains Plugin

---

src/events/index.ts
src/features/App.tsx
src/hooks/useEventBusForApp.ts
src/hooks/useEventBusForIDE.ts

- Problem: CodeLens are currently not supported in JetBrains
- Solution: Exposed actions to JetBrains with @reymondzzzz , also made a semantic renaming of `ideDoneStreaming` action to `ideIsChatStreaming` action, since `isStreaming` is being dispatched at this event on each change, not just on `doneStreaming`
- [[JB] add CodeLens](https://refact.fibery.io/Software_Development/Task/JB-add-CodeLens-80)

Feature: Adding CodeLens support to JetBrains

---

src/app/middleware.ts

- Problem: If `integrations.yaml` was written with syntax errors, we are not showing to user any error message
- Solution: Handling tools fetching in `middleware.ts` and setting an error message
- [/v1/tools can have `detail` message](https://refact.fibery.io/Software_Development/UI-UX-133#Task/v1-tools-can-have-detail-message-300)
- Step 1: Open a new chat
- Step 2: Go to `integrations.yaml`, paste this line of code: `hello: "aaaaaa`
- Step 3: Click on New Chat once more
- Step 4: There should be an error message from LSP in UI

Fix: Better errors for `integrations.yaml`

---

src/components/ChatForm/ChatForm.tsx

- Problem: Interacted state was outdated after form submission
- Solution: Reset of checkboxes' interacted state on form submit
- Step 1: Select lines and attach file
- Step 2: Send any message to the model
- Step 3: Reselect lines again
Expected Result: Checkboxes should be counting lines as usual
Actual Result: Checkboxes should be counting lines as usual

Fix: Resetting interacted state for Checkboxes on submit

---

package-lock.json
package.json

2.0.2-alpha.0

---

src/components/Chat/Chat.tsx
src/components/ChatContent/ChatContent.stories.tsx
src/components/ChatContent/ChatContent.tsx
src/components/ChatForm/ChatForm.stories.tsx
src/components/ChatForm/ChatForm.test.tsx
src/components/ChatForm/ChatForm.tsx

Fix by setting the position of the button to "absolute" and setting the "top" value to a negative value.
Run chat, check if the stop button causes ui jumps.

ui(stop button): make it "float" to stop the screen from jumping

---

src/features/Chat/Thread/utils.ts
src/services/refact/types.ts

New role for messages `cd_instruction`
Related to deterministic messages.

wip(cd instructions): allow `cd_instruciton` messages

---

src/features/Chat/Thread/actions.ts

- Problem: Sometimes model is returning an explanation of how it needs to generate a title, not the actual title.
- Solution: Adjusted prompt message to strictly set maximum length of title of 2-3 words.
- [Bug with a title summary - Here is a 2-3 word title](https://refact.fibery.io/Software_Development/UI-UX-133#Task/Bug-with-a-title-summary---Here-is-a-2-3-word-title-347)
- Step 1: Ask anything to chat
- Step 2: Title should be nicely generated
Additional testing is required.

Fix: Adjusted prompt for title generation

---

package-lock.json
package.json

2.0.3-alpha.1

---

src/components/IntegrationsView/IntegrationsView.tsx

- Additional description of integration setup sections (global, folder-specific)
-

Add some description text to setup integrations

---

src/app/middleware.ts
src/components/ChatLinks/ChatLinks.tsx
src/debugConfig.ts
src/features/Chat/Thread/actions.ts
src/features/Chat/Thread/reducer.ts
src/features/Chat/Thread/selectors.ts
src/features/Chat/Thread/types.ts
src/hooks/useSendChatRequest.ts
src/services/refact/chat.ts
src/services/refact/links.ts

Relies on this branch: https://github.com/smallcloudai/refact-lsp/pull/463
- Step 1:
- Step 2:
- ...

Project summary

---

src/components/ChatContent/ToolsContent.tsx
src/components/ChatContent/UserInput.tsx
src/components/ChatForm/ChatForm.tsx
src/components/DialogImage/DialogImage.tsx
src/components/DialogImage/index.ts
src/components/Dropzone/Dropzone.tsx
src/hooks/useAttachedImages.ts

- Add images with copy and paste
- Also let users click on an image to see it better
- Fixes the colour issue with collapsable trigger for multi model tools.
For image popups, run story book and go to `Chat content` then `multi modal`, then click on an image.
For copy and paste, find an image right click and `copy`, then in chat click on the form and right click `paste` the image should be added to the chat form.
Press submit and then click on the image in the user message.
https://refact.fibery.io/Software_Development/Current-Week-by-state-358#Task/UI-make-tool-calls-with-screenshots-better-494
and
https://refact.fibery.io/Software_Development/Current-Week-by-state-358#Task/UI-Paste-an-image-413

Copy paste images

---

.storybook/preview.tsx
src/components/ChatContent/ContextFiles.tsx
src/components/ChatContent/ToolsContent.tsx
src/components/Toolbar/Toolbar.tsx
src/lib/render/web.css

- Step 1:
- Step 2:
- ...
- Fixes #123
- Closes #456

add pointer for buttons and other clickable elements

---

src/components/ChatLinks/ChatLinks.tsx
src/services/refact/links.ts

duplicate requests being made when starting a new chat.
Open the network tab, click new chart, `/v1/links` should only be called once.
https://refact.fibery.io/Software_Development/Week1209-by-state-420#Task/UI-asks-for-links-twice-503

Fix links requests

---

src/components/ChatContent/ChatContent.tsx
src/components/ChatLinks/ChatLinks.tsx
src/components/SmartLink/SmartLink.tsx
src/hooks/index.ts
src/hooks/useGoToLink.ts
src/hooks/useLinksFromLsp.ts
src/hooks/useSmartLinks.ts
src/utils/index.ts
src/utils/isAbsolutePath.ts

Add a shared goto handler for Chat links and Smart links.
There are also other functions in the hook for handling `actions` and smart links,
Chat links should still work.
Smart links should still work and be able to handle go-to.

links Shared code 

---

src/debugConfig.ts
src/features/Chat/Thread/actions.ts

- Problem: title generation was broken because of chat responding in stream mode
- Solution: made title generation to work with stream
- [UI title generation is broken](https://refact.fibery.io/Software_Development/UI-UX-133#Task/UI-title-generation-is-broken-515)

Fix: Title Generation consumes stream

---

src/components/IntegrationsView/CustomFieldsAndWidgets.tsx
src/components/IntegrationsView/IntegrationCard.module.css
src/components/IntegrationsView/IntegrationForm/IntegrationAvailability.tsx
src/components/IntegrationsView/IntegrationForm/IntegrationForm.module.css
src/components/IntegrationsView/IntegrationForm/IntegrationForm.tsx
src/components/IntegrationsView/IntegrationsHeader.module.css
src/components/IntegrationsView/IntegrationsHeader.tsx
src/components/IntegrationsView/IntegrationsView.tsx
src/components/SmartLink/SmartLink.module.css
src/components/SmartLink/SmartLink.tsx
src/features/Integrations/renderIntegrationFormField.module.css
src/features/Integrations/renderIntegrationFormField.tsx

Small fixes to ui. Buttons, icon size, icon placement.
- Step 1:
- Step 2:
- ...
- Fixes #123
- Closes #456

Alpha UI fixes

---

src/__fixtures__/chat_links_response.ts
src/hooks/useLinksFromLsp.ts
src/services/refact/consts.ts
src/services/refact/links.ts

Commit link handler.
Adds a handler for commits.
- Step 1: make uncommitted change in a repo.
- Step 2: start the lsp and add the path to the repo to the `-w` parameter
- Step 3: start a chat, use agent mode.
- Step 4: there should be a commit link.
- Step 5: click it
- Step 6: see info about the commit being successful or not

Commit action

---

src/components/StatisticView/StatisticView.tsx

- Step 1:
- Step 2:
- ...
- Fixes #123
- Closes #456

Alpha fix stats sorting

---

src/__fixtures__/chat_links_response.ts
src/components/ChatLinks/ChatLinks.tsx
src/hooks/useLinksFromLsp.ts
src/services/refact/links.ts

link format has changed.
https://github.com/smallcloudai/refact-lsp/pull/498/files
- Step 1: Open chat in agent mode
- Step 2: See links :)

refactor(links): update link type

---

src/components/Toolbar/Dropdown.tsx
src/features/History/historySlice.ts

- There is no way to clear history in one click. Now it's possible via general dropdown menu of the application.
- [Implement a shortcut or debug-only button to clear history of chats](https://refact.fibery.io/Software_Development/Week1216-by-state-427#Task/Implement-a-shortcut-or-debug-only-button-to-clear-history-of-chats-500)

Feature: Clear history in one click

---

src/hooks/useSendChatRequest.ts

- Problem: `isWaiting` was blocking tool calls from execution and entire chat was frozen.
- Solution: On confirming tools, resetting state of `isWaiting` back to false.
- [🔴 UI Call Confirmation, deny, "Continue" button => 400 Bad Request](https://refact.fibery.io/Software_Development/Week1216-by-state-427#Task/UI-Call-Confirmation,-deny,-Continue-button-400-Bad-Request-579)
- Step 1: Make sure that your integration has `confirmation` settings set up:
```yaml
confirmation:
ask_user: []
deny: ['*']
```
- Step 2: Ask the model to call certain tool
- Step 3: Confirm/continue execution in Tool Confirmation popup
- Step 4: Chat should continue execution as usual.

Fix: Recalling tools after tool confirmation

---

src/components/IntegrationsView/Confirmation/Confirmation.tsx
src/components/IntegrationsView/Confirmation/index.ts
src/components/IntegrationsView/IntegrationForm/IntegrationForm.tsx
src/components/IntegrationsView/IntegrationsTable/ConfirmationTable.tsx
src/components/IntegrationsView/IntegrationsTable/ParametersTable.tsx
src/components/IntegrationsView/IntegrationsView.tsx
src/features/Integrations/renderIntegrationFormField.tsx
src/services/refact/integrations.ts

- Provides support for confirmation rules editing of desired integrations.
- [🔴 Integration page - deny and confirm editor](https://refact.fibery.io/Software_Development/Week1216-by-state-427#Task/Integration-page---deny-and-confirm-editor-537)
This PR provides minimal functional support of confirmation rules. It's not the final way of how would we treat those rules. Code needs to be refactored in a near future.

Feature: Confirmation Rules in Integrations

---

package-lock.json
package.json

2.0.3.alpha.7

---

src/components/ChatContent/ChatContent.tsx
src/components/IntegrationsView/IntegrationsView.tsx
src/features/History/historySlice.ts
src/features/Pages/pagesSlice.ts
src/services/refact/integrations.ts

Fix: Navigation back to integration's configuration & command names for services on intermediate page 

---

src/__fixtures__/chat_links_response.ts
src/hooks/useGoToLink.ts
src/services/refact/links.ts

Goto can be `newchat`, so a handler has been added for it.
I used a stub for this one because I couldn't get the `NEWCHAT` link.
- Step 1: Open chat
- Step 2: Click Project summary link
- Step 3: ...
- Step 4: click the new chat link (I'm not sure what it'll say).
https://refact.fibery.io/Software_Development/Release-6.1-433#Task/Project-summarization-has-NEWCHAT-link-594

New chat chat link

---

src/components/ChatContent/ChatContent.tsx
src/components/ChatLinks/ChatLinks.module.css
src/components/ChatLinks/ChatLinks.tsx

[x] Adds a blur effect to the content behind the button
[x] Moves the buttons a little lower
- Step 1: Start a chat or run storybook
- Step 2: Move content behind the chat link buttons.

ui(chat links): blur the background of the button

---

src/__fixtures__/integrations.ts
src/components/IntegrationsView/Confirmation/Confirmation.tsx
src/components/IntegrationsView/IntegrationForm/IntegrationForm.tsx
src/components/IntegrationsView/IntegrationsTable/ConfirmationTable.module.css
src/components/IntegrationsView/IntegrationsTable/ConfirmationTable.tsx
src/components/IntegrationsView/IntegrationsView.tsx
src/components/IntegrationsView/IntermediateIntegration/IntermediateIntegration.tsx
src/features/Chat/Thread/actions.ts
src/features/Integrations/renderIntegrationFormField.tsx
src/hooks/useGoToLink.ts
src/hooks/useLinksFromLsp.ts
src/services/refact/integrations.ts

- [VERIFIED AND STILL THERE -- UI save and return to config, doesn't load the updates values](https://refact.fibery.io/Software_Development/Week1223-by-state-436#Task/VERIFIED-AND-STILL-THERE----UI-save-and-return-to-config,-doesn't-load-the-updates-values-(and-we-wa-508)
- Step 1:
- Step 2:
- ...

Fix: Integration Setup page improvements & opening integrations from links

---

src/components/IntegrationsView/IntegrationDocker/IntegrationDocker.module.css
src/components/IntegrationsView/IntegrationDocker/IntegrationDocker.tsx
src/components/IntegrationsView/IntegrationForm/IntegrationForm.tsx

- Problem: Docker section was taking too much space if there is no connection to Docker Daemon.
- Solution: Simplification of current codebase, making small heading instead of big card with headings.
- [Integration page -- improvements pack](https://refact.fibery.io/Software_Development/Week1223-by-state-436#Task/Integration-page----improvements-pack-577)

Improvement: Making `no-connection` ErrorCard better in `IntegrationDocker` & Simplifications in IntegrationForm

---

src/components/IntegrationsView/Confirmation/Confirmation.tsx
src/components/IntegrationsView/IntegrationsTable/ConfirmationTable.module.css
src/components/IntegrationsView/IntegrationsTable/ConfirmationTable.tsx
src/components/IntegrationsView/IntegrationsTable/DefaultCell.tsx
src/components/IntegrationsView/IntegrationsTable/ParametersTable.tsx
src/debugConfig.ts
src/features/Integrations/Integrations.tsx

- Problem: Working experience with current parameters/confirmation tables is awful
- Solution: Memoization of table columns to make sure that entire table won't be rerendered on data state change :)
- [Integration page -- improvements pack](https://refact.fibery.io/Software_Development/Week1223-by-state-436#Task/Integration-page----improvements-pack-577)

Fix: Integration tables fixes

---

src/components/ChatContent/ContextFiles.tsx

- [UI context_files hide 1-1](https://refact.fibery.io/Software_Development/Week1223-by-state-436#Task/UI-context_files-hide-1-1-511)

Fix: Hiding file's lines if no lines are there

---

src/__fixtures__/chat_links_response.ts
src/services/refact/links.ts

New Link type to handle
```
{
"link_action": "post-chat",
"link_text": "Stop recommending integrations",
"link_tooltip": "",
"link_payload": {
"chat_meta": {
"chat_id": "",
"chat_remote": false,
"chat_mode": "CONFIGURE",
"current_config_file": "/Users/kot/code_aprojects/demotest/.refact/project_summary.yaml"
},
"messages": [
{
"role": "user",
"content": "Make recommended_integrations an empty list, follow the system prompt."
}
]
}
}
```
- Step 1:
- Step 2:
- ...
- Fixes #123
- Closes #456

post-chat Link type

---

src/features/Chat/Thread/actions.ts
src/hooks/useLinksFromLsp.ts

- Chat title generation is streamable, since we have already written logic to handle stream for titles
- [Chat title still doesn't work](https://refact.fibery.io/Software_Development/Release-6.1-433#Task/Chat-title-still-doesn't-work-617)

Fix: Chat title generation is streamable

---

src/components/ChatContent/useAutoScroll.ts

- Problem: long chat from history was opening at the very beginning
- Solution: scroll to the bottom on open
- [When opening the chat it goes to the first message, not to the end of the chat](https://refact.fibery.io/Software_Development/Task/When-opening-the-chat-it-goes-to-the-first-message,-not-to-the-end-of-the-chat-629)

Fix: scrolling into view on chat opening

---

src/components/Chat/Chat.tsx
src/components/ChatForm/ChatForm.tsx
src/components/ChatForm/actions.ts
src/components/ChatForm/useInputValue.ts
src/hooks/useLinksFromLsp.ts
src/hooks/useSendChatRequest.ts
src/services/refact/links.ts

- [UI Add support for 'post-chat` in links](https://refact.fibery.io/Software_Development/Task/UI-Add-support-for-'post-chat-in-links-615)
- [[UI & VSCode] CodeLens: Support multiple messages send/receive from customization.yaml](https://refact.fibery.io/Software_Development/Task/UI-VSCode-CodeLens-Support-multiple-messages-send-receive-from-customization.yaml-642)
- Step 1:
- Step 2:
- ...

Feat: Post Chat link functionality

---

src/components/ChatForm/ChatForm.tsx

The user should be able to continue typing in the text area while the response from the lsp are coming in.
Note: There are some protections against allowing the user to send the input while still streaming as this can cause 400 errors. 
- Step 1: Ask a question that results in an assistant message and tool results. 
- Step 2: Start typing in the textarea and start pressing enter.
- Step 3: the message should during the tool result phase.
https://refact.fibery.io/Software_Development/UI-chat-js-133#Task/Enable-input-box-when-streaming-647
There maybe be a visual glitch when repeatedly pushing enter where a `0` shows up for tools/attached files :/

feat(textarea): allow the user to continue typing while waiting for responses.

---

src/components/ChatContent/AssistantInput.tsx
src/components/ChatLinks/ChatLinks.tsx
src/components/Markdown/Markdown.tsx
src/utils/extractLinkFromPuzzle.ts

- Support for `🧩SETTINGS:service_npm_run_dev` links and refactoring of logic deciding which things to parse in Markdown component.
- [Convert 🧩SETTINGS:service_npm_run_dev to a link user can click](https://refact.fibery.io/Software_Development/Task/Convert-SETTINGS-service_npm_run_dev-to-a-link-user-can-click-619)

Feat: Puzzle links parsing in assistant messages

---

src/components/IntegrationsView/IntegrationForm/IntegrationForm.module.css
src/components/IntegrationsView/IntegrationForm/IntegrationForm.tsx
src/components/IntegrationsView/IntegrationsView.tsx

- [Integrations UI: Move smartlinks to the top section below enabled switch and delete configuration button](https://refact.fibery.io/Software_Development/Task/Integrations-UI-Move-smartlinks-to-the-top-section-below-enabled-switch-and-delete-configuration-but-657)
- [Compressed "project XX integrations" label](https://refact.fibery.io/Software_Development/Task/Compressed-project-XX-integrations-label-655)

Fix: Integration page UI adjustments

---

src/components/IntegrationsView/IntegrationForm/IntegrationForm.tsx
src/components/IntegrationsView/IntegrationsHeader.module.css

- [Cannot delete an integration config file if it's empty](https://refact.fibery.io/Software_Development/Release-6.1-433#Task/Cannot-delete-an-integration-config-file-if-it's-empty-661)

Improvement: Delete button addition for erroring integrations

---

src/components/ChatForm/ChatForm.tsx
src/components/ChatForm/RetryForm.tsx
src/components/ChatLinks/ChatLinks.tsx
src/hooks/useSmartLinks.ts

- [By editing an existing message in a chat, you can bypass the daily message limit](https://refact.fibery.io/Software_Development/Task/By-editing-an-existing-message-in-a-chat,-you-can-bypass-the-daily-message-limit-638)
- [Initial project summarization works even if the daily usage limit is reached](https://refact.fibery.io/Software_Development/Task/Initial-project-summarization-works-even-if-the-daily-usage-limit-is-reached-595)
- [Links from integration works even when day limit reached](https://refact.fibery.io/Software_Development/Task/Links-from-integration-works-even-when-day-limit-reached-597)
- All info for testing is self-explanatory in tickets on Fibery

Fix: Agent usage validation

---

src/components/ChatContent/useAutoScroll.ts
src/components/ChatForm/RetryForm.tsx

- [When scrolling up a long chat for the first time, the scroll button is not displayed](https://refact.fibery.io/Software_Development/Release-6.1-433#Task/When-scrolling-up-a-long-chat-for-the-first-time,-the-scroll-button-is-not-displayed-669)
- [By editing an existing message in a chat, you can bypass the daily message limit](https://refact.fibery.io/Software_Development/Release-6.1-433#Task/By-editing-an-existing-message-in-a-chat,-you-can-bypass-the-daily-message-limit-638)

Fix: scroll issues in IDEs and preventing submitting messages on keypress

---

src/components/Chat/Chat.tsx
src/components/ChatForm/ChatControls.tsx

- [Now quick/explore/agent is visible on the second chat turn and onwards](https://refact.fibery.io/Software_Development/Release-6.1-433#Task/Now-quick-explore-agent-is-visible-on-the-second-chat-turn-and-onwards-677)
- [After changes with "chat mode and model indicator" chat JSON copy menu disappeared](https://refact.fibery.io/Software_Development/Release-6.1-433#Task/After-changes-with-chat-mode-and-model-indicator-chat-JSON-copy-menu-disappeared-682)
We need to think about desired approach on showing controls to switch models and chat mode in runtime

Fix: Hiding chat controls in running chats

---

src/components/Chat/Chat.tsx

- [By resuming an existing interrupted message in a chat, you can bypass the daily message limit](https://refact.fibery.io/Software_Development/Release-6.1-433#Task/By-resuming-an-existing-interrupted-message-in-a-chat,-you-can-bypass-the-daily-message-limit-701)

Fix: Resume of chat with uncalled tools won't be possible if agent usage limit is exhausted

---

src/components/ChatForm/FilesPreview.tsx

When attaching an empty file `:0-0` would show up in the file preview area.
- Step 1: Create an empty file.
- Step 2: Copy the absolute path to this file
- Step 3: type `@file ` then paste the absolute path, 
- Step 4: press back arrow to get the completion area to show this file,
- Step 5: attach it. 
- Step 6: `:0-0` should no longer be shown in the file name.
- Closes https://refact.fibery.io/Software_Development/Task/UI-context_files-hide-1-1-511/comment=284

fix(empty preview files): remove. `:0-0` when the file is empty.

---

src/components/IntegrationsView/IntegrationForm/IntegrationForm.tsx
src/components/IntegrationsView/IntegrationsHeader.tsx
src/components/IntegrationsView/IntegrationsView.module.css

- [UI Smartlink enable only with tool](https://refact.fibery.io/Software_Development/Release-6.1-433#Task/UI-Smartlink-enable-only-with-tool-589)
- [chatjs - P3 - Misaligned Text in Integration Configuration Window  ](https://refact.fibery.io/Software_Development/Release-6.1-433#Task/chatjs---P3---Misaligned-Text-in-Integration-Configuration-Window-703)

Fix: Integrations page layout shifts and smartlinks issue

---

src/components/Toolbar/Toolbar.tsx
src/features/Chat/Thread/reducer.ts
src/features/History/historySlice.ts

- [Generated titles renaming](https://refact.fibery.io/Software_Development/Release-6.1-433#Task/Generated-titles-renaming-700)

Feature: Rename/delete functionality for chat threads within chat window

---

src/components/PageWrapper/PageWrapper.module.css

- [ChatJS - make chat printable](https://refact.fibery.io/Software_Development/Task/ChatJS---make-chat-printable-732)

Make better print styles for PDFs exporting

---

src/components/ChatForm/ToolConfirmation.tsx

- [P2 - ChatJS - Better UI for file patch confirmation](https://refact.fibery.io/Software_Development/Task/P2---ChatJS---Better-UI-for-file-patch-confirmation-729)

Feature: Better UI for Patch Confirmation

---

src/app/middleware.ts
src/components/Callout/Callout.tsx
src/components/ChatForm/ChatForm.tsx
src/features/App.tsx
src/features/Errors/errorsSlice.ts

- [P2 - UI - when we get 401 access denied error - prompt user to relogin](https://refact.fibery.io/Software_Development/Task/P2---UI---when-we-get-401-access-denied-error---prompt-user-to-relogin-711)
- Step 1: Start LSP binary with incorrect API key
- Step 2: Try to start new chat
- Step 3: New UI for authorization errors should appear
- Step 1: Change your API key to be incorrect in IDE Settings
- Step 2: Try to start new chat
- Step 3: New UI for authorization errors should appear

Feature: Different error message on authorization errors

---

src/components/ChatForm/ChatForm.tsx
src/hooks/useAttachedImages.ts
src/hooks/useCapsForToolUse.ts

- [P1 - UI - disable image upload for models that don't support multimodality](https://refact.fibery.io/Software_Development/Task/P1---UI---disable-image-upload-for-models-that-don't-support-multimodality-748)

Fix: Disable image upload functionality for models which don't support multimodality

---

src/features/AgentUsage/AgentUsage.tsx
src/hooks/useAgentUsage.ts

- [UI: Agent usage data should be retrieved from the server](https://refact.fibery.io/Software_Development/Release-6.1-433#Task/UI-Agent-usage-data-should-be-retrieved-from-the-server-719)

Fix: reload button for usage limits update

---

src/services/refact/caps.ts

- Refetch caps when starting a new chat.
- Step 1: Open a chat
- Step 2: Check the network tab
- Step 3: Open a new chat and caps should be fetched.

fix(caps): refetch caps on mount or arg change.

---

src/components/ChatForm/ChatForm.tsx
src/hooks/useAgentUsage.ts
src/hooks/useSmartLinks.ts

- Limit exhausted message was saying to switch to EXPLORE mode, but limits are across all modes now.
- Removed "switch to mode" part and unified limit exhausted messages to be just one single constant

Fix: Unified limit exhausted message across app & adjusted text

---

src/components/ChatForm/ChatForm.tsx

- [Turn off internet -- empty error message](https://refact.fibery.io/Software_Development/UI-chat-js-133#Task/Turn-off-internet----empty-error-message-759)

Fix: Offline info message

---

src/utils/extractLinkFromPuzzle.test.ts
src/utils/extractLinkFromPuzzle.ts

- This PR fixes issues with rendering of Windows-like paths for puzzle links

Fix: Puzzle links path management

---

src/components/ChatForm/ChatForm.tsx
src/components/Dropzone/Dropzone.tsx
src/components/Toolbar/Toolbar.tsx
src/components/Tour/Tour.tsx
src/features/App.tsx

- [Bring tooltips to the same style](https://refact.fibery.io/Software_Development/Task/Bring-tooltips-to-the-same-style-796)
- [Misaligned arrow in product tour overlay](https://refact.fibery.io/Software_Development/Task/Misaligned-arrow-in-product-tour-overlay-794)
- [Tour blinking at start](https://refact.fibery.io/Software_Development/Task/Tour-blinking-at-start-795)
- [Typo in tour](https://refact.fibery.io/Software_Development/Sprint-2025-01-27-471#Task/Typo-in-tour-793)

Fix: Tour hotfixes

---

src/components/ChatForm/AgentCapabilities.tsx
src/components/ChatForm/ChatControls.tsx
src/components/ChatForm/ChatForm.tsx
src/features/Chat/Thread/actions.ts
src/features/Chat/Thread/reducer.ts
src/features/Chat/Thread/selectors.ts
src/features/Chat/Thread/types.ts
src/hooks/useSendChatRequest.ts
src/services/refact/chat.ts

- [UI: Add popup to control automatic patch and rollback functionality](https://refact.fibery.io/Software_Development/Task/UI-Add-popup-to-control-automatic-patch-and-rollback-functionality-801)

Feature: Better controls for Agentic Features

---

src/__fixtures__/caps.ts
src/__fixtures__/msw.ts
src/__tests__/ChatCapsFetchError.test.tsx
src/__tests__/DeleteChat.test.tsx
src/__tests__/PinMessages.test.tsx
src/__tests__/RestoreChat.test.tsx
src/__tests__/StartNewChat.test.tsx
src/__tests__/UserSurvey.test.tsx
src/components/ChatForm/ChatForm.tsx
src/features/Chat/Chat.test.tsx

- [Chat is working even when No models available](https://refact.fibery.io/Software_Development/Task/Chat-is-working-even-when-No-models-available-766)

Fix: Preventing send of the chat if no models are available for the user

---

src/components/IntegrationsView/DisplayIntegrations/IntegrationCard.tsx
src/components/IntegrationsView/Header/IntegrationsHeader.tsx
src/components/IntegrationsView/IntegrationForm/FormFields.tsx
src/components/IntegrationsView/IntegrationForm/IntegrationForm.tsx
src/components/IntegrationsView/IntegrationsTable/ArgumentsTable.tsx
src/components/IntegrationsView/IntegrationsTable/ConfirmationTable.tsx
src/components/IntegrationsView/IntegrationsTable/DefaultCell.tsx
src/components/IntegrationsView/IntegrationsTable/EnvironmentVariablesTable.tsx
src/components/IntegrationsView/IntegrationsTable/ParametersTable.tsx
src/components/IntegrationsView/IntegrationsView.tsx
src/components/IntegrationsView/hooks/useFormAvailability.ts
src/components/IntegrationsView/hooks/useIntegrations.ts
src/features/Integrations/IntegrationFormField.tsx
src/services/refact/integrations.ts
src/services/refact/types.ts
src/utils/getIntegrationInfo.ts
src/utils/validateSnakeCase.ts

- Step 1:
- Step 2:
- ...
- Fixes #123
- Closes #456

Feature: MCP support

---

src/components/Markdown/CodeBlock.tsx
src/utils/trimIndent.ts
src/utils/utils.test.tsx

- Showing "No content" and disabling copying if file is empty in the code block

fix: showing 'No content' if file content is undefined

---

src/features/Config/configSlice.ts
src/features/Login/LoginPage.tsx
src/hooks/useLogin.ts
src/hooks/useLogout.ts

- Step 1: Login in JB
- Step 2: Login in VScode

fix(cloud login): set address url when logging in through cloud

---

src/hooks/useCheckpoints.ts

- [add telemetry for revert handler usage](https://refact.fibery.io/Software_Development/Sprint-2025-01-27-471#Task/add-telemetry-for-revert-handler-usage-742)

feat(telemetry): sending telemetry for agent rollback actions

---

src/app/store.ts
src/features/App.tsx
src/features/PatchesAndDiffsTracker/patchesAndDiffsTrackerSlice.ts
src/hooks/usePatchesAndDiffEventsForIDE.ts

Jetbrains needs to know when the lsp has changes files in the project.
A new slice + middleware has been added to track patches and diffs, and a hooks has been added to check the files and send the to the id.
Note: there's a related PR in JB for this.
https://github.com/smallcloudai/refact-intellij/pull/220
- Step 1: Use the patch tool in JB
- Step 2: The file should be reloaded once the patch is applied.

Send info about file changes to the ide

---

src/__fixtures__/checkpoints.ts
src/components/Callout/Callout.tsx
src/features/Checkpoints/CheckpointButton.tsx
src/features/Checkpoints/Checkpoints.stories.tsx
src/features/Checkpoints/Checkpoints.tsx
src/features/Checkpoints/checkpointsSlice.ts
src/features/Checkpoints/types.ts
src/hooks/useCheckpoints.ts
src/hooks/usePreviewCheckpoints.ts
src/services/refact/checkpoints.ts
src/services/refact/consts.ts

Current implementation previews content first, and when user hits rollback, then it applies.
- [Issue when rollback not accepted and reload IDE](https://refact.fibery.io/Software_Development/Sprint-2025-02-10-495#Task/Issue-when-rollback-not-accepted-and-reload-IDE-821)

Feature: Better implementation Agent Rollback

---

src/components/ChatForm/ToolConfirmation.tsx
src/hooks/useSendChatRequest.ts

- ["Patch files without confirmation" slider is not working text_edit](https://refact.fibery.io/Software_Development/Sprint-2025-02-10-495#Task/Patch-files-without-confirmation-slider-is-not-working-text_edit-823)

Fix: Patch improvements support

---

src/hooks/useCapsForToolUse.ts

fix: filtered out o3-mini from models list

---

src/components/IntegrationsView/hooks/useIntegrations.ts

- Problem: form values were checked in incorrect way for MCP integration
- Solution: adjusted `onChange` for the form and internal checks in `useEffect` when any data changes
- Step 1: Open MCP integration configuration
- Step 2: Try to write something into `command` (form should enable)
- Step 3: Try to clear `command` field (form should disable)
- Step 4: Try to write something into MCP arguments table (form should enable, when input is unfocused)
- Step 5: Try to write something into `command` (form should keep it's enabled state)
- Step 6: Try to clear written before MCP arguments (form should still keep it's enabled state)
- Step 7: Clear out `command` field (form should disable)

Fix: Hotfixes for MCP Integration Support

---

src/features/Chat/Thread/actions.ts
src/features/Chat/Thread/types.ts
src/hooks/useLinksFromLsp.ts

- Preventing invalidation of `/v1/links` request, by sending generic `AGENT` mode to links request payload, if `threadMode` is `AGENT` or `THINKING_AGENT`
- [List of uncommited changes dissapears when "reasoning" slider is turned on](https://refact.fibery.io/Software_Development/Task/List-of-uncommited-changes-dissapears-when-reasoning-slider-is-turned-on-851)

Fix: Uncommitted changes warning disappears in Thinking Mode

---

src/components/ChatForm/ChatControls.tsx

- [UI: Show o3-mini explicitly as a reasoning model in switch](https://refact.fibery.io/Software_Development/Task/UI-Show-o3-mini-explicitly-as-a-reasoning-model-in-switch-861)

Fix: Show o3-mini as reasoning model
